In [ ]:
import numpy as np

temperature=np.array([25, 28, 31, 35, 38, 27, 33, 40])
temperature=temperature + 2
fahrenheit=(9/5) * temperature + 32
greater=temperature[temperature > 32]
count=np.sum(temperature > 32)
print("Updated temperatures:", temperature)
print("Fahrenheit:", fahrenheit)
print("Readings greater than 32:", greater)
print("Count:", count)

Updated temperatures: [27 30 33 37 40 29 35 42]
Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32: [33 37 40 35 42]
Count: 5


In [ ]:
steps=np.array([[5000, 6200, 7100],
                  [8000, 7500, 9000],
                  [4500, 5100, 4800],
                  [9000, 8500, 9500]])
print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum:", np.max(steps))
print("Minimum:", np.min(steps))
print("Total for each day:", np.sum(steps, axis=0))
print("Total for each user:", np.sum(steps, axis=1))
pos=np.unravel_index(np.argmax(steps), steps.shape)
print("Maximum position:", pos)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum: 9500
Minimum: 4500
Total for each day: [26500 27300 30400]
Total for each user: [18300 24500 14400 27000]
Maximum position: (3, 2)


In [ ]:
original=np.array([1,2,3,4,5,6])
subset=original[1:4]
subset[0]=999
print("Original:", original)
print("Subset:", subset)
copied=original[1:4].copy()
copied[0]=500
print("Original:", original)
print("Copied:", copied)

Original: [  1 999   3   4   5   6]
Subset: [999   3   4]
Original: [  1 999   3   4   5   6]
Copied: [500   3   4]


In [ ]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:,1])
print("Rows 1-2 and columns 2-3:", matrix[1:3,2:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3: [[ 7  8]
 [11 12]]


In [ ]:
matrix=np.arange(1,13).reshape(3,4)
flat_array=matrix.flatten()
ravel_array=matrix.ravel()
print("Flatten:",flat_array)
print("Ravel:",ravel_array)
ravel_array[0]=100
print("After ravel change:")
print(matrix)
print(ravel_array)
flat_array[1]=200
print("After flatten change:")
print(matrix)
print(flat_array)

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
After ravel change:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[100   2   3   4   5   6   7   8   9  10  11  12]
After flatten change:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[  1 200   3   4   5   6   7   8   9  10  11  12]


In [ ]:
matrix = np.arange(1,13).reshape(3,4)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int32


In [ ]:
X = np.array([[6,70,3],
              [5,50,6],
              [8,80,2],
              [4,30,8]])
y = np.array([40,65,30,85])



print("Shape:", X.shape)
print("Dimensions:", X.ndim)

print("Transpose:")
print(X.T)

print("X.T @ X:")
print(X.T @ X)

inverse = np.linalg.inv(X.T @ X)

print("Inverse:")
print(inverse)

Shape: (4, 3)
Dimensions: 2
Transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]


In [ ]:

X=np.array([[6,70,3],
              [5,50,6],
              [8,80,2],
              [4,30,8]])

y=np.array([40,65,30,85])

beta=np.linalg.inv(X.T @ X) @ X.T @ y

print("Coefficients:", beta)

new_user=np.array([5,40,7])

prediction=new_user@beta
print("Predicted assistance score:", prediction)

Coefficients: [-0.15921454  0.14083853 10.06302242]
Predicted assistance score: 75.27862544779117
